---
title: "P8105 Final Project Proposal"
output: github_document
date: "2024-11-07"
---

### Group Members 

1. Xuanyu Guo (xg2451) 
2. Riya Nadkarni (rcn2115)
3. Christiana Odewumi(coo2124)
4. Shehzrin Shah (ss6985)

### Project Title 

Analysis of Gun Violence in the United States in 2014-2023

### Motivation for Project 

Gun violence is a public health and safety issue in the United States, which consistently experiences higher levels of firearm-related incidents compared to other developed countries. This project seeks to provide an analysis of gun violence across dimensions (i.e., temporal, geographic, and demographic factors). With the constitutional right to bear arms embedded in American society, understanding patterns and trends in gun violence could help guide policymakers, law enforcement, and public health officials in informing strategies involving gun violence. 

Objectives: 

 - Analyze trends in gun violence over time 
 - Identify high-risk time periods for gun violence incidents
 - Assess differences in gun violence across states and cities (identifying regions with disproportionately high incident rates)
 - Assess factors associated with high incident rates in certain demographics and areas 

### Intended Final Products 

- Interactive webpage that has the overview of the project and findings (including interactive charts and maps) 
- A written report that describes our analysis and findings in detail (i.e., trends, patterns about gun violence in the United States) that can be found on webpage 
- Screencast to introduce the project, findings, visualizations that can be found on webpage 
- Individual peer assessment 

### Anticipated Data Sources 

- https://www.gunviolencearchive.org/
- https://www2.census.gov/programs-surveys/popest/datasets/

### Planned Analyses / Visualizations / Coding Challenges

- Data(Web) scraping 
- Data cleaning/wrangling
- Trend analysis to observe changes over years or seasonal trends in gun violence (see whether incidents are increasing or decreasing over time)  
- Temporal and spatial analysis 
-- Which times of the year (seasons, holidays, years) and which locations 
-- Identify states and cities with the highest frequency of mass shootings.
-- Heatmaps of incidents by state/city 
- Demographic/incident characteristics analysis to analyze different types of gun violence incidence and demographics affected 
-- Bar charts to compare incident types and demographic impacts


### Planned Timeline 

- **November 8 by 1:00 pm**: Team Registration & Proposal Document Submission on GitHub
- **November 11 - 15**: Project Review Meeting 
- **November 11 - 20**: Data collection, cleaning, initial data analysis and visualizations 
- **November 20 - 30**: Full data analysis, coding completion, focus on screencast
- **December 1 - 6**: final report, webpage completion, peer assessment 
